#!/usr/bin/env bash
#install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www/html
sudo echo "Holberton School" >> /var/www/html/index.nginx-debian.html
sudo service nginx start
