#!/usr/bin/env bash
# Process and PID file
# shellcheck disable=SC2078

sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid

while $1
do
	echo "To infinity and beyond"
	trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
	sleep 2
done
