#!/usr/bin/env bash
# 4 bad luck 8 good luck

i=0
while [ $i -lt "10" ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"

	elif [ $i -eq 7 ]
	then
		echo "good luck"

	else
		echo "Holberton School"
	fi
	((i++))
done
