#!/usr/bin/env bash
# use nginx as nginx user
sudo pkill nginx
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.config


sudo sed -i 's/80/8080' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
