#!/usr/bin/env bash
# use nginx as nginx user
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data/user nginx/' etc/nginx/ngin.conf
sudo -u nginx service nginx start
